language: c

matrix:
  include:
  - dist: xenial
    env: BASE=7.0 STATIC=shared
  - dist: xenial
    env: BASE=7.0 EXTRA=CMD_CXXFLAGS=-std=c++11
  - dist: trusty
    env: BASE=7.0 STATIC=shared CMPLR=clang
  - dist: xenial
    env: BASE=7.0 STATIC=static
  - dist: xenial
    env: BASE=3.15 STATIC=shared
  - dist: xenial
    env: BASE=3.14 STATIC=shared
  - dist: xenial
    env: BASE=3.14 STATIC=static
  - dist: trusty
    env: KSER=3.x KVER=3.2.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
  - dist: trusty
    env: KSER=3.x KVER=3.16.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
  - dist: xenial
    env: KSER=4.x KVER=4.9.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
  - dist: xenial
    env: KSER=4.x KVER=4.19.67 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"

install:
 - ./.ci/prepare-epics.sh
 - ./.ci/prepare-linux.sh
script:
 - ./.ci/build-epics.sh
 - ./.ci/build-linux.sh
