language: cpp
compiler: gcc
dist: xenial

cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local

addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang

matrix:
  include:
  - dist: xenial
    env: BASE=7.0 STATIC=shared
  - dist: xenial
    env: BASE=7.0 EXTRA=CMD_CXXFLAGS=-std=c++11
  - dist: trusty
    env: BASE=7.0 STATIC=shared CMPLR=clang
  - dist: xenial
    env: BASE=7.0 STATIC=static
  - dist: xenial
    env: BASE=3.15 STATIC=shared
  - dist: xenial
    env: BASE=3.14 STATIC=shared
  - dist: xenial
    env: BASE=3.14 STATIC=static
  - dist: trusty
    env: KSER=3.x KVER=3.2.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
  - dist: trusty
    env: KSER=3.x KVER=3.16.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
  - dist: xenial
    env: KSER=4.x KVER=4.9.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
  - dist: xenial
    env: KSER=4.x KVER=4.19.67 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
  - dist: xenial
    env: KSER=5.x KVER=5.5.19 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"

install:
 - if [ "$BASE" ]; then ./.ci/travis/prepare.sh; fi
 - ./.ci-local/prepare-linux.sh
script:
 - if [ "$BASE" ]; then ./.ci/travis/build.sh; fi
 - ./.ci-local/build-linux.sh
